name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Install Deps
        run: sudo apt-get install pulseaudio

      - name: Check Out
        uses: actions/checkout@v2
      
      - name: export game
        uses: firebelley/godot-export@v1.2.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.2.1/Godot_v3.2.1-stable_linux_headless.64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.2.1/Godot_v3.2.1-stable_export_templates.tpz
          godot_template_version: 3.2.1.stable
          relative_project_path: ./
          create_release: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
        run: >
          -H "Authorization: Bearer $NETLIFY_TOKEN" \
          --data-binary "@/home/runner/.local/share/godot/dist/HTML5.zip" \
          https://api.netlify.com/api/v1/sites